# Generated by Django 4.1.5 on 2023-01-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='ClassType_id',
            new_name='class_type_id',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='Discipline_id',
            new_name='discipline_id',
        ),
    ]
