# Generated by Django 4.1.5 on 2023-01-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_classtype_id_occupation_class_type_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormatLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.car')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('number', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('passport_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.passport')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.role')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_of_training', models.CharField(max_length=255)),
                ('end_date_of_training', models.CharField(max_length=255)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.instructor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.brand')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('format_learning_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.formatlearning')),
                ('program_learning_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.programlearning')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.student')),
                ('timetable_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.model'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.transmission'),
        ),
    ]
