# Generated by Django 4.1.5 on 2023-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_car_formatlearning_instructor_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
