# Generated by Django 4.1.5 on 2023-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='date_of_birth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passport',
            name='date_of_issue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='place_of_birth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
