# Generated by Django 4.1.5 on 2023-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_passport_date_of_birth_passport_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='driving_experience',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
