# Generated by Django 4.1.5 on 2023-01-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_instructor_driving_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
