# Generated by Django 4.1.5 on 2023-02-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.user'),
            preserve_default=False,
        ),
    ]
