# Generated by Django 4.1.5 on 2023-02-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_user_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
