# Generated by Django 4.1.5 on 2023-02-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_user_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='role_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(default=2, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
