# Generated by Django 4.1.5 on 2023-02-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_userinfo_role_id_userinfo_slug_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='media_car/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.car'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.userinfo'),
        ),
        migrations.AlterField(
            model_name='model',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.passport'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(null=True, upload_to='media_user/%Y/%m/%d/'),
        ),
    ]
