# Generated by Django 4.1.5 on 2023-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_car_model_id_alter_car_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Марка'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='classtype',
            options={'verbose_name': 'Тип занятия'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина'},
        ),
        migrations.AlterModelOptions(
            name='formatlearning',
            options={'verbose_name': 'Формат обучения'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Инструктор'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Занятие'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Паспорты'},
        ),
        migrations.AlterModelOptions(
            name='programlearning',
            options={'verbose_name': 'Программа обучения'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name': 'Коробки передач'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
