# Generated by Django 4.1.5 on 2023-02-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_brand_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.group'),
            preserve_default=False,
        ),
    ]
