# Generated by Django 4.1.5 on 2023-02-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_group_timetable_id_timetable_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='slug',
        ),
    ]
