# Generated by Django 4.1.5 on 2023-02-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_userinfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
