# Generated by Django 4.1.5 on 2023-02-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_userinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.group'),
        ),
    ]
