# Generated by Django 4.1.5 on 2023-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_timetable_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date_of_birth',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date_of_training',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date_of_training',
            field=models.DateField(auto_now=True, max_length=255),
        ),
    ]
