# Generated by Django 4.1.5 on 2023-02-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_passport_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='class_type_id',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='discipline_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='occupation_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='end_date_of_training',
            field=models.DateField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ClassType',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
